server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://rm-2ze0yodsc49x32687uo.mysql.rds.aliyuncs.com:3306/ci_bei_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: testuser
    password: Test_pw123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl